### PR TITLE
Adding Python language

### PR DESCRIPTION
**Pull request by sahildua2305**
@ashish1294 I tried adding Python language to the tool. It's not working fine on my system. Can you please check and point out what's wrong with it?

### CODE REVIEW

**Comment by ashish1294** [comment]
Everything looks okay. But you will also have to edit the prog.py file to handle the python case.

It should work then. Note I am on vacation for a week and I will be able to help with code after that only.

Great work (y)

**Comment by sahildua2305** [comment]
Just added Python to prog.py too. Still not working for me. Do check it once you're back.

**Comment by ashish1294** [comment]
Can you confirm where exactly is it not working ? Which judge ? Which language ?

Also was it working before you made changes ?

**Comment by sahildua2305** [comment]
Yes, it was working before making changes. None of the buttons work after
making changes. Can you check on local machine once?

Sahil
http://sahildua.com

**Comment by ashish1294** [comment]
Can you post the console log ? It will be immensely useful.

Unfortunately when I wrote original code I was using Linux, Now I am on Mac. So it's different. Will run a VM but that might take some time.

**Comment by sahildua2305** [comment]
Okay, I'll do that in a while.

Sahil
http://sahildua.com

**Comment by sahildua2305** [comment]
Ok, I just checked, as I click on any button on SPOJ/Codeforces, Code-now host gets disconnected.
`Code-Now Host disconnected !! Hope You are enjoying this log :P`

**Comment by ashish1294** [comment]
Ensure you have python installed, prog.py is executable and double-check the extension id. This is probably due to mismatch extension ids

**Comment by sahildua2305** [comment]
I have Python installed, prog.py is executable. Checked the extension id, there was a conflict. Removed it; made same, still the same error.

**Comment by ashish1294** [comment]
It's working for me on a VM. Please remove all files. Start afresh and check.

**Comment by ashish1294** [comment]
Here is a debugging tip : Start your chrome / chromium browser on command line. That way you will be able to check the error generated by python program on the terminal.

**Comment by sahildua2305** [comment]
Deleted entire repo, installed fresh. Not working. No error on either of the consoles. This is getting weird.

**Comment by ashish1294** [comment]
Make sure to delete .code-now folder.

**Comment by ashish1294** [comment]
I tested it again on a stand alone Linux system and found it working again. So I will go ahead and merge it.

**Comment by ashish1294** [comment]
@sahildua2305 : I just spotted a silly bug. The template name should have been py_template.py. you named it as python_template.py causing the prog.py to raise exception. I have fixed this.

**Pull request merged**
